version: "3.9"

services:
  db:
    image: postgres:alpine
    container_name: restaurant
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env.prod
    volumes:
      - db-postgres:/var/lib/postgresql/data
    networks:
      - my-net
  app:
    build:
      context: .
    env_file:
      - .env.prod
    container_name: api
    command: bash -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./app:/home/app
    networks:
      - my-net

volumes:
  db-postgres:
    driver: local

  cache:
    driver: local

networks:
  my-net:
    external: true