"""added price column

Revision ID: 5e45d67e24d2
Revises: 09096943c77d
Create Date: 2024-01-22 14:11:30.925370

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e45d67e24d2'
down_revision: str | None = '09096943c77d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('price', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'price')
    # ### end Alembic commands ###
