"""refactored indexes to str

Revision ID: 7900604f7c28
Revises: 499641c320a1
Create Date: 2024-01-25 20:13:47.814506

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '7900604f7c28'
down_revision: str | None = '499641c320a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
