"""added price column

Revision ID: b972e36846c3
Revises: 5e45d67e24d2
Create Date: 2024-01-22 15:15:33.464240

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b972e36846c3'
down_revision: str | None = '5e45d67e24d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'price',
                    existing_type=sa.NUMERIC(),
                    type_=sa.Float(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'price',
                    existing_type=sa.Float(),
                    type_=sa.NUMERIC(),
                    existing_nullable=False)
    # ### end Alembic commands ###
