"""refactored indexes to str

Revision ID: e1b266d3c126
Revises: 7900604f7c28
Create Date: 2024-01-25 20:20:17.568707

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e1b266d3c126'
down_revision: str | None = '7900604f7c28'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
