"""empty message

Revision ID: f2477eac3723
Revises: e1b266d3c126
Create Date: 2024-01-29 16:18:42.638918

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = 'f2477eac3723'
down_revision: str | None = 'e1b266d3c126'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
